#H2
#spring.datasource.url=jdbc:h2:testdb
hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.connection.driver_class=org.h2.Driver
hibernate.connection.url=jdbc:h2:./note
hibernate.connection.autocommit=true


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true